protein_seq:
  _target_: cortex.model.root.TransformerEncoderRoot
  corruption_process:
    _target_: cortex.corruption.MaskCorruptionProcess
  tokenizer_transform:
    _target_: cortex.transforms.HuggingFaceTokenizerTransform
    tokenizer:
      _target_: cortex.tokenization.ProteinSequenceTokenizerFast
  max_len: 256
  out_dim: ${embed_dim}
  embed_dim: ${embed_dim}
  channel_dim: ${channel_dim}
  num_blocks: 2
  num_heads: 4
  dropout_prob: ${dropout_prob}
  pos_encoding: true
  train_transforms: null
  eval_transforms: null
