exclude: ".egg-info|_skbuild"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml|templates/.*.yaml
      - id: check-yaml
        name: check-yaml-mkdocs
        # --unsafe is a workaround for the use of !! in mkdocs.yml.
        args: [--unsafe]
        files: mkdocs.yml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        name: ruff
        args: [ --fix ]
      - id: ruff-format
