_target_: cortex.task.RegressionTask
task_name: log_fluorescence
tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: Rostlab/prot_bert_bfd
  do_lower_case: false
transform:
  _target_: cortex.transforms.HFTokenizerTransform
  tokenizer: ${task.tokenizer}
  max_length: 512
  padding: max_length
  truncation: true
  return_tensors: pt
  text_field: primary
  # Protein sequences use spaces between amino acids for BERT models
  add_spaces_between_chars: true
