log_fluorescence_hf:
  _target_: cortex.task.RegressionTask
  # Single root key mapping for HF tokenized inputs
  input_map:
    protein_seq: []  # Empty list since we'll use tokenized inputs directly
  outcome_cols: ["label"]
  root_key: protein_seq
  corrupt_train_inputs: false
  corrupt_inference_inputs: false
  nominal_label_var: 0.01

  data_module:
    _target_: cortex.data.data_module.HFTaskDataModule
    dataset_config:
      _target_: datasets.load_dataset
      path: "proteinglm/fluorescence_prediction"
      name: default
      trust_remote_code: true
    batch_size: ${fit.batch_size}
    num_workers: ${num_workers}
    drop_last: true
    text_field: "seq"
    label_field: "label"
    add_spaces_between_chars: true
    tokenization_batch_size: 1000
    tokenization_num_proc: 4
