defaults:
  - general_settings: default
  - logging: default
  - model_globals: default
  - roots: [protein_seq_cnn]
  - trunk: default
  - branches: [protein_property_cnn, generation]
  - tree: protein_model
  - tasks:
    # - protein_property/aggreg_pml
    - protein_property/hic_rt
    - generation/gingko_gdpa1
  - _self_

fit:
  batch_size: 32

trainer:
  _target_: lightning.Trainer
  accelerator: cpu
  max_epochs: 128
  # devices: 1
  # devices: 8
  # strategy: ddp
  num_sanity_val_steps: 0
  precision: 32

tree:
  _recursive_: false
  fit_cfg:
    reinitialize_roots: true
    linear_probing: false
    weight_averaging: null
    optimizer:
      _target_: torch.optim.Adam
      lr: 1e-3
      weight_decay: 0.0
      betas: [0.99, 0.999]
      fused: false
    lr_scheduler:
      _target_: transformers.get_cosine_schedule_with_warmup
      num_warmup_steps: 10
      num_training_steps: ${trainer.max_epochs}

ensemble_size: 2
channel_dim: 64
dropout_prob: 0.0
tasks:
  # folding:
  #   stability:
  #     ensemble_size: ${ensemble_size}
  protein_property:
    # aggreg_pml:
    #   ensemble_size: ${ensemble_size}
    hic_rt:
      ensemble_size: ${ensemble_size}
  generation:
    gingko_gdpa1:
      ensemble_size: 1

train_on_everything: false
linear_probing: false
dataset_root_dir: /home/stantos5/scratch/datasets
download_datasets: true
num_workers: 0

ckpt_name: ${exp_name}_${job_name}
