defaults:
  - general_settings: default
  - logging: default
  - model_globals: default
  - roots: [protein_seq_encoder]
  - trunk: default
  - branches: [folding_encoder, protein_property_encoder, generation]
  - tree: protein_model
  - tasks:
    - protein_property/log_fluorescence
    - folding/stability
    - generation/tape_combined
  - _self_

fit:
  batch_size: 128

trainer:
  _target_: lightning.Trainer
  accelerator: gpu
  max_epochs: 128
  devices: 1
  # devices: 8
  # strategy: ddp
  num_sanity_val_steps: 0
  # precision: 16

tree:
  _recursive_: false
  fit_cfg:
    reinitialize_roots: true
    linear_probing: false
    weight_averaging: null
    optimizer:
      _target_: torch.optim.Adam
      lr: 3e-4
      weight_decay: 0.
      betas: [0.99, 0.999]
      fused: false
    lr_scheduler:
      _target_: transformers.get_cosine_schedule_with_warmup
      num_warmup_steps: 10
      num_training_steps: ${trainer.max_epochs}

tasks:
  folding:
    stability:
      ensemble_size: ${ensemble_size}
  protein_property:
    log_fluorescence:
      ensemble_size: ${ensemble_size}
  generation:
    tape_combined:
      ensemble_size: 1

train_on_everything: false
linear_probing: false
dataset_root_dir: /home/stantos5/scratch/datasets
download_datasets: true
num_workers: 2

ckpt_name: ${exp_name}_${job_name}
