from ._protein_constants import (
    AB_AG_COMPLEX_COL,
    ANTIGEN_COL,
    ANTIGEN_COMPLEX_TOKEN,
    CANON_AMINO_ACIDS,
    VARIABLE_HEAVY_CHAIN_TOKEN,
    VARIABLE_HEAVY_COL,
    VARIABLE_LIGHT_CHAIN_TOKEN,
    VARIABLE_LIGHT_COL,
)

ALIGNMENT_GAP_TOKEN = "-"
COMPLEX_SEP_TOKEN = "."
NULL_TOKENS = ["<null_1>"]


__all__ = [
    "AB_AG_COMPLEX_COL",
    "ALIGNMENT_GAP_TOKEN",
    "ANTIGEN_COL",
    "ANTIGEN_COMPLEX_TOKEN",
    "CANON_AMINO_ACIDS",
    "COMPLEX_SEP_TOKEN",
    "NULL_TOKENS",
    "VARIABLE_HEAVY_CHAIN_TOKEN",
    "VARIABLE_HEAVY_COL",
    "VARIABLE_LIGHT_CHAIN_TOKEN",
    "VARIABLE_LIGHT_COL",
]
