feature_dim: 32
kernel_size: 3
data_dir: ./cache

tree:
  _target_: cortex.model.tree.SequenceModelTree
roots:
  protein_seq:
    _target_: cortex.model.root.Conv1dRoot
    tokenizer_transform:
      _target_: cortex.transforms.HuggingFaceTokenizerTransform
      tokenizer:
        _target_: cortex.tokenization.ProteinSequenceTokenizerFast
    max_len: 256
    embed_dim: ${feature_dim}
    channel_dim: ${feature_dim}
    out_dim: ${feature_dim}
    num_blocks: 2
    kernel_size: ${kernel_size}
trunk:
  _target_: cortex.model.trunk.SumTrunk
branches:
  protein_property:
    _target_: cortex.model.branch.Conv1dBranch
    out_dim: 8
    channel_dim: ${feature_dim}
    num_blocks: 0
    kernel_size: ${kernel_size}
tasks:
  protein_property:
    log_fluorescence:
      _target_: cortex.task.RegressionTask
      input_map:
        protein_seq: ['tokenized_seq']
      outcome_cols: ['log_fluorescence']
      root_key: protein_seq
      ensemble_size: 1
      data_module:
        _target_: cortex.data.data_module.TaskDataModule
        _recursive_: false
        batch_size: 2
        dataset_config:
          _target_: cortex.data.dataset.TAPEFluorescenceDataset
          root: ${data_dir}
          download: true
          train: ???
