defaults:
  - tree: sequence_model
  - roots: [protein_seq]
  - trunk: sum_trunk
  - branches: [protein_property, protein_generation]
  - tasks:
    - log_fluorescence
    - protein_seq
  - guidance_objective: log_fluorescence
  - optim: lambo

feature_dim: 32
kernel_size: 3
batch_size: 32
max_epochs: 2
data_dir: ./.cache
wandb_mode: offline
random_seed: 42
num_steps: 8
num_samples: 16

trainer:
  _target_: lightning.Trainer
  max_epochs: ${max_epochs}
  num_sanity_val_steps: 1
